Region: us-east-2
Image:
  Os: ubuntu2004
  CustomAmi: ami-08ddea673d79b8450
HeadNode:
  InstanceType: t2.micro
  Networking:
    SubnetId: subnet-0ecabcbdfec66e462
  Ssh:
    KeyName: hummingbird
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: queue1
    ComputeResources:
    - Name: t2micro
      InstanceType: t2.micro
      MinCount: 0
      MaxCount: 10
    Networking:
      SubnetIds:
      - subnet-0b670e56e895c5e57
