Region: us-east-2
Image:
  Os: ubuntu2004
  CustomAmi: ami-08ddea673d79b8450
HeadNode:
  InstanceType: t2.micro
  Networking:
    SubnetId: subnet-0ecabcbdfec66e462
  Ssh:
    KeyName: hummingbird
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: queue1
    ComputeResources:
    - Name: t2micro
      InstanceType: t2.micro
      MinCount: 0
      MaxCount: 10
    Networking:
      SubnetIds:
      - subnet-0b670e56e895c5e57
SharedStorage:
  - MountDir: hummingbird
    Name: fsxhummingbird
    StorageType: FsxLustre
    FsxLustreSettings:
      StorageCapacity: 1200
      ExportPath: s3://cmat-thrust1/Marklein
      ImportPath: s3://cmat-thrust1/Marklein
DirectoryService:
  DomainName: dc=hummingbird,dc=emory,dc=edu
  DomainAddr: ldap://172.31.6.230,ldap://172.31.28.23
  PasswordSecretArn: arn:aws:secretsmanager:region-id:123456789012:secret:MicrosoftAD.Admin.Password
  DomainReadOnlyUser: cn=ReadOnly,ou=Users,ou=HUMMINGBIRD,dc=hummingbird,dc=emory,dc=edu
  AdditionalSssdConfigs:
    ldap_auth_disable_tls_never_use_in_production: True